
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Apr 12 19:14:42 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 23;
  public static final int LTE = 39;
  public static final int CONST = 6;
  public static final int CASE = 33;
  public static final int LPAREN = 12;
  public static final int SEMI = 8;
  public static final int CONTINUE = 25;
  public static final int NUM_CONST = 22;
  public static final int MINUS = 41;
  public static final int RPAREN = 13;
  public static final int AND = 48;
  public static final int LT = 37;
  public static final int OR = 50;
  public static final int COMMA = 9;
  public static final int CLASS = 7;
  public static final int INC = 46;
  public static final int DIV = 40;
  public static final int PLUS = 11;
  public static final int IF = 20;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 3;
  public static final int EQUAL = 10;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 43;
  public static final int MOD = 42;
  public static final int NUMBER = 18;
  public static final int NEQ = 47;
  public static final int BREAK = 31;
  public static final int IDENT = 19;
  public static final int VOID = 5;
  public static final int EQ = 49;
  public static final int GTE = 36;
  public static final int SWITCH = 30;
  public static final int COLON = 35;
  public static final int LBRACE = 14;
  public static final int ELSE = 21;
  public static final int LSQUARE = 16;
  public static final int ENUM = 29;
  public static final int READ = 27;
  public static final int RSQUARE = 17;
  public static final int WHILE = 26;
  public static final int RBRACE = 15;
  public static final int EXTENDS = 32;
  public static final int PROG = 2;
  public static final int QUESTION = 45;
  public static final int BOOL_CONST = 24;
  public static final int DEC = 51;
  public static final int GT = 44;
  public static final int PRINT = 4;
  public static final int DO = 34;
}

